version: '2'
services:
    web:
        build: .
        ports:
            - "127.0.0.1:5000:5000"
        volumes:
            - .:/web
        environment:
            - PORT:5000
        expose:
            - "5000"
